import type { TemplateTheme, TemplateCategory } from './theme'

export { mergeWithATS } from './theme'
export type { TemplateTheme, TemplateCategory, LayoutType, SectionTitleStyle, BulletStyle, SkillDisplay, HeaderStyle, ExperienceStyle } from './theme'
export { default as TemplateRenderer } from './TemplateRenderer'
export { default as CoverLetterRenderer } from './CoverLetterRenderer'

export type TemplateDefinition = {
  id: string
  label: string
  description: string
  category: TemplateCategory
  theme: TemplateTheme
}

export const TEMPLATES: Record<string, TemplateDefinition> = {
  modern: {
    id: 'modern',
    label: 'Modern',
    description: 'Clean single-column with bold indigo accents',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1a1a2e', secondary: '#6c63ff', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'default',
      experienceStyle: 'default',
      spacing: { pagePadding: '48px 44px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  clean: {
    id: 'clean',
    label: 'Clean',
    description: 'Minimal single-column with sky-blue accents',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#0f172a', secondary: '#0ea5e9', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'stacked',
      experienceStyle: 'default',
      spacing: { pagePadding: '48px 44px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  warm: {
    id: 'warm',
    label: 'Warm',
    description: 'Earthy single-column with terracotta-orange accents',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1c1917', secondary: '#ea580c', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'default',
      experienceStyle: 'compact',
      spacing: { pagePadding: '48px 44px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  forest: {
    id: 'forest',
    label: 'Forest',
    description: 'Nature-inspired single-column with green accents',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#14532d', secondary: '#16a34a', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'stacked',
      experienceStyle: 'compact',
      spacing: { pagePadding: '48px 44px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  rose: {
    id: 'rose',
    label: 'Rose',
    description: 'Elegant single-column with rose-pink accents',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1f1f1f', secondary: '#e11d48', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'centered',
      experienceStyle: 'default',
      spacing: { pagePadding: '48px 44px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  executive: {
    id: 'executive',
    label: 'Executive',
    description: 'Professional single-column with slate-gray accents',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1e293b', secondary: '#94a3b8', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'centered',
      experienceStyle: 'default',
      spacing: { pagePadding: '48px 44px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  sidebar: {
    id: 'sidebar',
    label: 'Sidebar',
    description: 'Two-column layout with indigo sidebar',
    category: 'design',
    theme: {
      layout: 'two-col',
      colors: { accent: '#1e1b4b', secondary: '#818cf8', background: '#ffffff', text: '#1a1a1a', textMuted: '#777777' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'border-bottom',
      bullet: 'dot',
      skillDisplay: 'pill',
      headerStyle: 'default',
      experienceStyle: 'default',
      spacing: { pagePadding: '44px 28px', sidebarPadding: '44px 20px', sectionGap: '12px' },
    },
  },
  compact: {
    id: 'compact',
    label: 'Compact',
    description: 'Space-efficient two-column with amber accents',
    category: 'design',
    theme: {
      layout: 'two-col',
      colors: { accent: '#18181b', secondary: '#f59e0b', background: '#ffffff', text: '#1a1a1a', textMuted: '#777777' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'border-bottom',
      bullet: 'dot',
      skillDisplay: 'pill',
      headerStyle: 'default',
      experienceStyle: 'compact',
      spacing: { pagePadding: '44px 28px', sidebarPadding: '44px 20px', sectionGap: '12px' },
    },
  },
  atsClassic: {
    id: 'atsClassic',
    label: 'Classic ATS',
    description: 'Plain single-column optimized for applicant tracking systems',
    category: 'minimal',
    theme: {
      layout: 'single',
      colors: { accent: '#000000', secondary: '#333333', background: '#ffffff', text: '#111111', textMuted: '#444444' },
      fonts: { name: "'Arial', 'Helvetica', sans-serif", heading: "'Arial', 'Helvetica', sans-serif", body: "'Arial', 'Helvetica', sans-serif", mono: "'Courier New', monospace" },
      fontSize: { name: '24px', title: '11px', sectionHeading: '11px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'accent-bar',
      bullet: 'dash',
      skillDisplay: 'comma-list',
      headerStyle: 'default',
      experienceStyle: 'default',
      spacing: { pagePadding: '46px 44px', sidebarPadding: '44px 20px', sectionGap: '10px' },
    },
  },
  atsProfessional: {
    id: 'atsProfessional',
    label: 'Professional ATS',
    description: 'Clean single-column with navy accents for ATS',
    category: 'minimal',
    theme: {
      layout: 'single',
      colors: { accent: '#1a365d', secondary: '#2d3748', background: '#ffffff', text: '#111111', textMuted: '#444444' },
      fonts: { name: "'Arial', 'Helvetica', sans-serif", heading: "'Arial', 'Helvetica', sans-serif", body: "'Arial', 'Helvetica', sans-serif", mono: "'Courier New', monospace" },
      fontSize: { name: '24px', title: '11px', sectionHeading: '11px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'accent-bar',
      bullet: 'dash',
      skillDisplay: 'comma-list',
      headerStyle: 'default',
      experienceStyle: 'default',
      spacing: { pagePadding: '46px 44px', sidebarPadding: '44px 20px', sectionGap: '10px' },
    },
  },
  atsMinimal: {
    id: 'atsMinimal',
    label: 'Minimal ATS',
    description: 'Ultra-plain single-column for maximum ATS compatibility',
    category: 'minimal',
    theme: {
      layout: 'single',
      colors: { accent: '#2d2d2d', secondary: '#555555', background: '#ffffff', text: '#111111', textMuted: '#444444' },
      fonts: { name: "'Arial', 'Helvetica', sans-serif", heading: "'Arial', 'Helvetica', sans-serif", body: "'Arial', 'Helvetica', sans-serif", mono: "'Courier New', monospace" },
      fontSize: { name: '24px', title: '11px', sectionHeading: '11px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'accent-bar',
      bullet: 'dash',
      skillDisplay: 'comma-list',
      headerStyle: 'default',
      experienceStyle: 'default',
      spacing: { pagePadding: '46px 44px', sidebarPadding: '44px 20px', sectionGap: '10px' },
    },
  },

  /* ── Single Column (new) ── */

  minimalist: {
    id: 'minimalist',
    label: 'Minimalist',
    description: 'Ultra-clean with border-bottom titles, dash bullets, and comma-separated skills',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#181818', secondary: '#6b7280', background: '#ffffff', text: '#1a1a1a', textMuted: '#6b7280' },
      fonts: { name: "'Inter', sans-serif", heading: "'Inter', sans-serif", body: "'Inter', sans-serif", mono: "'JetBrains Mono', monospace" },
      fontSize: { name: '24px', title: '10px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'border-bottom',
      bullet: 'dash',
      skillDisplay: 'comma-list',
      headerStyle: 'stacked',
      experienceStyle: 'default',
      spacing: { pagePadding: '48px 48px', sidebarPadding: '44px 20px', sectionGap: '16px' },
    },
  },
  bold: {
    id: 'bold',
    label: 'Bold',
    description: 'High-contrast serif name, red accents, large typography',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#000000', secondary: '#dc2626', background: '#ffffff', text: '#111111', textMuted: '#525252' },
      fonts: { name: "'DM Serif Display', serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '30px', title: '12px', sectionHeading: '13px', body: '11px', small: '10px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'centered',
      experienceStyle: 'cards',
      spacing: { pagePadding: '44px 40px', sidebarPadding: '44px 20px', sectionGap: '16px' },
    },
  },

  /* ── Two Column (new) ── */

  contrast: {
    id: 'contrast',
    label: 'Contrast',
    description: 'Two-column with dark sidebar, orange accents, pill skills',
    category: 'design',
    theme: {
      layout: 'two-col',
      colors: { accent: '#171717', secondary: '#f97316', background: '#ffffff', text: '#1a1a1a', textMuted: '#777777' },
      fonts: { name: "'Fraunces', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'accent-bar',
      bullet: 'dot',
      skillDisplay: 'pill',
      headerStyle: 'default',
      experienceStyle: 'timeline',
      spacing: { pagePadding: '40px 24px', sidebarPadding: '40px 16px', sectionGap: '12px' },
    },
  },
  split: {
    id: 'split',
    label: 'Split',
    description: 'Even two-column split, sage-green, border-bottom titles, badge skills',
    category: 'design',
    theme: {
      layout: 'two-col',
      colors: { accent: '#1a2e1a', secondary: '#65a30d', background: '#fafaf9', text: '#1a1a1a', textMuted: '#777777' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'border-bottom',
      bullet: 'dash',
      skillDisplay: 'badge',
      headerStyle: 'default',
      experienceStyle: 'cards',
      spacing: { pagePadding: '40px 24px', sidebarPadding: '40px 16px', sectionGap: '12px' },
    },
  },

  /* ── ATS (new) ── */

  atsHybrid: {
    id: 'atsHybrid',
    label: 'Hybrid ATS',
    description: 'ATS-friendly with underline titles, dot bullets, comma-list skills',
    category: 'minimal',
    theme: {
      layout: 'single',
      colors: { accent: '#1e3a5f', secondary: '#3b82f6', background: '#ffffff', text: '#111111', textMuted: '#444444' },
      fonts: { name: "'Arial', 'Helvetica', sans-serif", heading: "'Arial', 'Helvetica', sans-serif", body: "'Arial', 'Helvetica', sans-serif", mono: "'Courier New', monospace" },
      fontSize: { name: '24px', title: '11px', sectionHeading: '11px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'comma-list',
      headerStyle: 'default',
      experienceStyle: 'default',
      spacing: { pagePadding: '46px 44px', sidebarPadding: '44px 20px', sectionGap: '12px' },
    },
  },

  /* ── Creative ── */

  portfolio: {
    id: 'portfolio',
    label: 'Portfolio',
    description: 'Teal accents, accent-bar titles, badge skills, Fraunces display font',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#0d3b3b', secondary: '#14b8a6', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Fraunces', Georgia, serif", heading: "'Bricolage Grotesque', sans-serif", body: "'Bricolage Grotesque', sans-serif", mono: "'IBM Plex Mono', monospace" },
      fontSize: { name: '30px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'accent-bar',
      bullet: 'dot',
      skillDisplay: 'badge',
      headerStyle: 'centered',
      experienceStyle: 'cards',
      spacing: { pagePadding: '44px 40px', sidebarPadding: '44px 20px', sectionGap: '18px' },
    },
  },
  visual: {
    id: 'visual',
    label: 'Visual',
    description: 'Violet accents, underline titles, pill skills, tinted background',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#2e1065', secondary: '#8b5cf6', background: '#faf5ff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Fraunces', Georgia, serif", heading: "'Bricolage Grotesque', sans-serif", body: "'Bricolage Grotesque', sans-serif", mono: "'IBM Plex Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'underline',
      bullet: 'dot',
      skillDisplay: 'pill',
      headerStyle: 'centered',
      experienceStyle: 'timeline',
      spacing: { pagePadding: '44px 40px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  gradient: {
    id: 'gradient',
    label: 'Gradient',
    description: 'Rose-red accent-bar titles, dash bullets, badge skills, compact spacing',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#431407', secondary: '#e11d48', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Fraunces', Georgia, serif", heading: "'Bricolage Grotesque', sans-serif", body: "'Bricolage Grotesque', sans-serif", mono: "'IBM Plex Mono', monospace" },
      fontSize: { name: '28px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'accent-bar',
      bullet: 'dash',
      skillDisplay: 'badge',
      headerStyle: 'default',
      experienceStyle: 'compact',
      spacing: { pagePadding: '44px 38px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  magazine: {
    id: 'magazine',
    label: 'Magazine',
    description: 'Editorial feel with coral accents, dash bullets, pill skills, large type',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1c1917', secondary: '#f43f5e', background: '#fffcf9', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '32px', title: '12px', sectionHeading: '13px', body: '11px', small: '10px' },
      sectionTitle: 'underline',
      bullet: 'dash',
      skillDisplay: 'pill',
      headerStyle: 'centered',
      experienceStyle: 'default',
      spacing: { pagePadding: '48px 44px', sidebarPadding: '44px 20px', sectionGap: '20px' },
    },
  },

  /* ── Academic ── */

  research: {
    id: 'research',
    label: 'Research',
    description: 'Navy & gold, border-bottom titles, comma-list skills, serif body',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#0f172a', secondary: '#eab308', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Lora', Georgia, serif", heading: "'Lora', Georgia, serif", body: "'Source Sans 3', sans-serif", mono: "'IBM Plex Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'border-bottom',
      bullet: 'dot',
      skillDisplay: 'comma-list',
      headerStyle: 'stacked',
      experienceStyle: 'timeline',
      spacing: { pagePadding: '48px 48px', sidebarPadding: '44px 20px', sectionGap: '16px' },
    },
  },
  teaching: {
    id: 'teaching',
    label: 'Teaching',
    description: 'Warm amber, underline titles, dash bullets, badge skills, cream paper',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1c1917', secondary: '#d97706', background: '#fefce8', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Lora', Georgia, serif", heading: "'Lora', Georgia, serif", body: "'Source Sans 3', sans-serif", mono: "'IBM Plex Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '11px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'dash',
      skillDisplay: 'badge',
      headerStyle: 'stacked',
      experienceStyle: 'cards',
      spacing: { pagePadding: '44px 44px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  publication: {
    id: 'publication',
    label: 'Publication',
    description: 'Scholarly indigo, accent-bar titles, comma-list skills, cool slate bg',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1e1b4b', secondary: '#6366f1', background: '#f8fafc', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Lora', Georgia, serif", heading: "'Lora', Georgia, serif", body: "'Source Sans 3', sans-serif", mono: "'IBM Plex Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'accent-bar',
      bullet: 'dot',
      skillDisplay: 'comma-list',
      headerStyle: 'default',
      experienceStyle: 'default',
      spacing: { pagePadding: '48px 48px', sidebarPadding: '44px 20px', sectionGap: '16px' },
    },
  },

  /* ── Timeline ── */

  chronological: {
    id: 'chronological',
    label: 'Chronological',
    description: 'Amber accents, underline titles, plain bullets (no marker), badge skills',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1c1917', secondary: '#d97706', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Playfair Display', Georgia, serif", heading: "'DM Sans', Arial, sans-serif", body: "'DM Sans', Arial, sans-serif", mono: "'DM Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '12px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'plain',
      skillDisplay: 'badge',
      headerStyle: 'stacked',
      experienceStyle: 'timeline',
      spacing: { pagePadding: '44px 40px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  functionalTimeline: {
    id: 'functionalTimeline',
    label: 'Functional Timeline',
    description: 'Cyan accents, accent-bar titles, plain bullets, pill skills',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#0f172a', secondary: '#06b6d4', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Inter', sans-serif", heading: "'Inter', sans-serif", body: "'Inter', sans-serif", mono: "'JetBrains Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '11px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'accent-bar',
      bullet: 'plain',
      skillDisplay: 'pill',
      headerStyle: 'default',
      experienceStyle: 'timeline',
      spacing: { pagePadding: '44px 40px', sidebarPadding: '44px 20px', sectionGap: '16px' },
    },
  },

  /* ── Tech ── */

  developer: {
    id: 'developer',
    label: 'Developer',
    description: 'Monospace name, neon green, accent-bar titles, comma-list skills',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#0a0a0a', secondary: '#22c55e', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'JetBrains Mono', monospace", heading: "'Inter', sans-serif", body: "'Inter', sans-serif", mono: "'JetBrains Mono', monospace" },
      fontSize: { name: '24px', title: '10px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'accent-bar',
      bullet: 'dash',
      skillDisplay: 'comma-list',
      headerStyle: 'default',
      experienceStyle: 'compact',
      spacing: { pagePadding: '40px 36px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  devops: {
    id: 'devops',
    label: 'DevOps',
    description: 'Slate & electric blue, border-bottom titles, plain bullets, badge skills',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#0f172a', secondary: '#3b82f6', background: '#f8fafc', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'JetBrains Mono', monospace", heading: "'Inter', sans-serif", body: "'Inter', sans-serif", mono: "'JetBrains Mono', monospace" },
      fontSize: { name: '24px', title: '10px', sectionHeading: '11px', body: '10px', small: '9px' },
      sectionTitle: 'border-bottom',
      bullet: 'plain',
      skillDisplay: 'badge',
      headerStyle: 'stacked',
      experienceStyle: 'compact',
      spacing: { pagePadding: '40px 36px', sidebarPadding: '44px 20px', sectionGap: '14px' },
    },
  },
  dataScience: {
    id: 'dataScience',
    label: 'Data Science',
    description: 'Violet & indigo, underline titles, plain bullets, comma-list skills',
    category: 'design',
    theme: {
      layout: 'single',
      colors: { accent: '#1a1a2e', secondary: '#8b5cf6', background: '#ffffff', text: '#1a1a1a', textMuted: '#555555' },
      fonts: { name: "'Inter', sans-serif", heading: "'Inter', sans-serif", body: "'Inter', sans-serif", mono: "'JetBrains Mono', monospace" },
      fontSize: { name: '26px', title: '11px', sectionHeading: '11px', body: '10.5px', small: '9.5px' },
      sectionTitle: 'underline',
      bullet: 'plain',
      skillDisplay: 'comma-list',
      headerStyle: 'centered',
      experienceStyle: 'compact',
      spacing: { pagePadding: '44px 40px', sidebarPadding: '44px 20px', sectionGap: '16px' },
    },
  },
}

export type TemplateKey = keyof typeof TEMPLATES

export function getTemplate(key: string): TemplateDefinition {
  return TEMPLATES[key] || TEMPLATES.modern
}
